/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MakertplaceImport } from './routes/makertplace'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const MakertplaceRoute = MakertplaceImport.update({
  id: '/makertplace',
  path: '/makertplace',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/makertplace': {
      id: '/makertplace'
      path: '/makertplace'
      fullPath: '/makertplace'
      preLoaderRoute: typeof MakertplaceImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/makertplace': typeof MakertplaceRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/makertplace': typeof MakertplaceRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/makertplace': typeof MakertplaceRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/makertplace'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/makertplace'
  id: '__root__' | '/' | '/makertplace'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MakertplaceRoute: typeof MakertplaceRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MakertplaceRoute: MakertplaceRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/makertplace"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/makertplace": {
      "filePath": "makertplace.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
